# Generated by Django 4.1.7 on 2023-03-26 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_question', models.CharField(max_length=300)),
                ('vote_date', models.DateTimeField(verbose_name='published date')),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_field', models.CharField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
                ('vote_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.question')),
            ],
        ),
    ]
