# Generated by Django 4.1.7 on 2023-03-26 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_field',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=10)),
                ('vote_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.question')),
            ],
        ),
    ]
