# Generated by Django 4.1.7 on 2023-03-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0002_alter_choice_choice_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='vote_question',
        ),
    ]
