# Generated by Django 4.1.7 on 2023-04-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0003_remove_name_vote_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vote_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='user_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='name',
            old_name='user_name',
            new_name='student_name',
        ),
    ]
