# Generated by Django 4.1.7 on 2023-04-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0007_remove_uploadimage_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
