# Generated by Django 4.1.7 on 2023-04-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0008_uploadimage_question_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voteapp.question'),
        ),
    ]
