# Generated by Django 4.1.7 on 2023-04-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0009_alter_uploadimage_image_alter_uploadimage_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
