# Generated by Django 4.1.7 on 2023-05-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0011_image_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Gender', models.CharField(max_length=2)),
                ('Student_id', models.IntegerField(default=0)),
                ('birth_date', models.CharField(max_length=255)),
                ('Street', models.TextField()),
                ('Hometown', models.TextField()),
                ('Class', models.TextField()),
                ('start_date', models.DateField()),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
