# Generated by Django 4.1.7 on 2023-05-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0012_usersdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='voteapp.question'),
        ),
    ]
