# Generated by Django 4.1.7 on 2023-05-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voteapp', '0014_alter_usersdetail_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdetail',
            name='question',
        ),
    ]
